### ISSUE TITLE
Costa rica dataset shrinks

### ISSUE THREAD

**Issue by sun9700** [cvjena/costarica-moths#1]
In paper: Fine-grained Recognition Datasets for Biodiversity Analysis
There are 3224 images in Costa rica dataset
However, there are only 2310 in imagelist.txt
could the author explain the shrinks?
thanks！

**Comment by MarcelSimon** [comment]
Hi!
We updated and cleaned up the dataset, please see our updated publication for reference: http://hera.inf-cv.uni-jena.de:6680/pdf/Rodner15:FRD.pdf  (press F5 if you still see the old version)

**Comment by sun9700** [comment]
thanks

**Comment by sun9700** [comment]
@MarcelSimon there are 990 1s in tr_ID.txt, please update update it to 1732, thanks!

num of train: 990, num of test: 1320

**Comment by MarcelSimon** [comment]
Sorry for the late reply. I just checked everything and it seems that there was a mistake in the paper. 990 is the correct number of training images in the cleaned dataset. The accuracy reported in the paper was computed with the dataset as it is provided here in the repository and hence should match.
