### ISSUE TITLE
error in tr_ID.txt

### ISSUE THREAD

**Issue by sun9700** [cvjena/costarica-moths#2]
there are 990 1s in tr_ID.txt, num of train: 990, num of test: 1320
please update update train samples to 1732, thanks!

**Comment by MarcelSimon** [comment]
Duplicate of #1 

I'm working on this issue and the update will come soon

**Comment by sun9700** [comment]
Sorry for the duplication. Thanks for your effort!

**Comment by sun9700** [comment]
@MarcelSimon is there any news? What about release the ground-truth without train/test split?
